### ISSUE TITLE
Animation incoming component when user scroll from top to bottom

### ISSUE THREAD

**Issue by naufaldi** [naufaldi/next-landing-vpn#12]
Example animation:
[Logos Website](https://logos-fest.vercel.app/)

**Comment by Abhijeet03s** [comment]
Hey, @naufaldi assign this issue to me.

**Comment by corners2wall** [comment]
@naufaldi , I wanna do this. Assign to me

**Comment by naufaldi** [comment]
oke, good luck @corners2wall
