### ISSUE TITLE
Add Favicon and OG Tags

### ISSUE THREAD

**Issue by naufaldi** [naufaldi/next-landing-vpn#16]
for better SEO, we should add things like
- Favicon
- Meta Tags
- OG Tags 

example in typescript is like 
[SEO Components](https://github.com/theodorusclarence/ts-nextjs-tailwind-starter/blob/main/src/components/Seo.tsx)

**Comment by Debarpan08** [comment]
Would you please assign this to me, Sir?

**Comment by Debarpan08** [comment]
!assign

**Comment by naufaldi** [comment]
oke, goodluck
