### ISSUE TITLE
Add Animation to Landingpage

### ISSUE THREAD

**Issue by naufaldi** [naufaldi/next-landing-vpn#5]
Add animation to Landingpage. You can use
- Framermotion
- AOS
- GSAP

Example:
- [x] #11
- [x] #12

**Comment by Shivam164** [comment]
@naufaldi  Hey, I would like to work on this. Please assign this to me.

**Comment by naufaldi** [comment]
done! Good luck!

**Comment by Shivam164** [comment]
@naufaldi How far can I go with these animations?
