### ISSUE TITLE
Upgrade to Newest version for Tailwind and NextJS

### ISSUE THREAD

**Issue by naufaldi** [naufaldi/next-landing-vpn#6]
upgrade landingpage to newest version of Tailwind and NextJS
- Tailwind ver 3.18
- NextJS ver 12.3

**Comment by iam-vipin** [comment]
assign it to me 
i will do it

**Comment by iam-vipin** [comment]
i will install latest version of Tailwind  and nextJs

**Comment by naufaldi** [comment]
oke, good luck!
